//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sokoban_014.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sokoban_014.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap GND {
            get {
                object obj = ResourceManager.GetObject("GND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap HumanB {
            get {
                object obj = ResourceManager.GetObject("HumanB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap HumanF {
            get {
                object obj = ResourceManager.GetObject("HumanF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap HumanL {
            get {
                object obj = ResourceManager.GetObject("HumanL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap HumanR {
            get {
                object obj = ResourceManager.GetObject("HumanR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Point {
            get {
                object obj = ResourceManager.GetObject("Point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Road {
            get {
                object obj = ResourceManager.GetObject("Road", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Game Clear !!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringMsgFinalStage {
            get {
                return ResourceManager.GetString("StringMsgFinalStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 스테이지로 이동합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringMsgNextStage {
            get {
                return ResourceManager.GetString("StringMsgNextStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 스테이지 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgNext {
            get {
                return ResourceManager.GetString("StringQMsgNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No 다음 스테이지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgNextNoCap {
            get {
                return ResourceManager.GetString("StringQMsgNextNoCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 스테이지로 이동하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgNextWhat {
            get {
                return ResourceManager.GetString("StringQMsgNextWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 스테이지?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgNextWhatCap {
            get {
                return ResourceManager.GetString("StringQMsgNextWhatCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 시작하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgRestart {
            get {
                return ResourceManager.GetString("StringQMsgRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 시작?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringQMsgRestartCap {
            get {
                return ResourceManager.GetString("StringQMsgRestartCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTitleCount {
            get {
                return ResourceManager.GetString("StringTitleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SokoBan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTitleGame {
            get {
                return ResourceManager.GetString("StringTitleGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTitleStage {
            get {
                return ResourceManager.GetString("StringTitleStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTitleTotalCount {
            get {
                return ResourceManager.GetString("StringTitleTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Stage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StringTitleTotalStage {
            get {
                return ResourceManager.GetString("StringTitleTotalStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
